Add handling for WKT as extent
wetransform/adv-inspire-alignments pull request #47
Opened 2021-04-29 06:27 UTC by JohannaOtt

WGS-918 / SVC-750

@stempler Do we need to take anything specific into account with the use of the snippet and the AdV using the gradle setup?

2021-05-20 13:44 UTC, florianesser requested changes

2021-05-20 13:44 UTC, florianesser commented on annex-2-3/mappings/LandUse/ALKIS2INSPIRE_ELU.halex
> +Hinweis zur Angabe einer WKT-Geometrie des Bundeslandes zur korrekten HAnhabung von ExistingLandUseDataSet.extent:&#xD;
*Handhabung

2021-05-20 13:44 UTC, florianesser commented on annex-2-3/mappings/LandUse/ALKIS2INSPIRE_ELU.halex
> +	Mit der Transformation wird die Datei "extentBundesland.groovy" bereitgestellt. Um den INSPIRE-Datensatz vollständig korrekt zu erzeugen, muss dort der Platzhalter [..] mit einer WKT-Geometrie Ihres
I tried that with a real-world example (Landesgrenze Hessen), and it failed with the message below. I think we have to think of an alternative approach, as I assume the WKT string of most Landesgrenzen will exceed the limit.

![image](https://user-images.githubusercontent.com/1867607/118988955-ef33c800-b981-11eb-82a4-b7a6569c70c8.png)

2021-05-21 06:22 UTC, JohannaOtt commented on annex-2-3/mappings/LandUse/ALKIS2INSPIRE_ELU.halex
> +Hinweis zur Angabe einer WKT-Geometrie des Bundeslandes zur korrekten HAnhabung von ExistingLandUseDataSet.extent:&#xD;
Good catch, thanks!

2021-05-21 06:26 UTC, JohannaOtt commented on annex-2-3/mappings/LandUse/ALKIS2INSPIRE_ELU.halex
> +	Mit der Transformation wird die Datei "extentBundesland.groovy" bereitgestellt. Um den INSPIRE-Datensatz vollständig korrekt zu erzeugen, muss dort der Platzhalter [..] mit einer WKT-Geometrie Ihres
That is an issue indeed. I only tested with smaller geometries.
What about asking them to provide the boundaries in the source foulder in an xml file using an xsd defined by us and read it as additional source data?
In this case we could again provide the xml file and they would only need to fill in the geometry. What do you think?

2021-05-27 15:12 UTC, JohannaOtt commented on annex-2-3/mappings/LandUse/ALKIS2INSPIRE_ELU.halex
> +	Mit der Transformation wird die Datei "extentBundesland.groovy" bereitgestellt. Um den INSPIRE-Datensatz vollständig korrekt zu erzeugen, muss dort der Platzhalter [..] mit einer WKT-Geometrie Ihres
I implemented a different approach using a csv file.

2021-05-27 15:13 UTC, JohannaOtt commented
@florianesser We would also need to adapt the gradle handling in order to make sure that the file "extentBundesland.csv" is included in every run of the ELU alignment, right?

2021-06-09 19:01 UTC, florianesser commented
> @florianesser We would also need to adapt the gradle handling in order to make sure that the file "extentBundesland.csv" is included in every run of the ELU alignment, right?

Yes, I've added support for that to `build.gradle`

2021-06-10 06:25 UTC, JohannaOtt commented
@florianesser Should we move the csv schema to a URL? Currently, the local path on my machine is still included in the halex files.

2021-06-10 11:31 UTC, florianesser approved these changes
LGTM

2021-06-10 11:31 UTC, merged