Fix/verwgem lowerlevelunit
wetransform/adv-inspire-alignments pull request #52
Opened 2021-08-25 10:11 UTC by florianesser

**Don't merge! Needs rebase after #50 is merged**

With the previous implementation, all `au:lowerLevelUnit` elements for 5th order administrative units ("Verwaltungsgemeinschaften") looked like

```
<au:lowerLevelUnit xlink:href="#AdministrativeUnit_null"/>
```

Also reverts references to test source data that is not available in the `testdaten/` directory.

2021-11-26 07:56 UTC, JohannaOtt requested changes

2021-11-26 07:56 UTC, JohannaOtt commented on annex-1/mappings6.0/AdministrativeUnits/aaa-au-kommunalesGebiet.halex
> +    <resource action-id="eu.esdihumboldt.hale.io.schema.read.target" provider-id="eu.esdihumboldt.hale.io.xsd.reader">
There are two imports for the target schema - one using http, one using https (in line 29).
Since https://github.com/wetransform/adv-inspire-alignments/pull/48, https is supposed to be used.

2022-01-10 16:37 UTC, florianesser commented on annex-1/mappings6.0/AdministrativeUnits/aaa-au-kommunalesGebiet.halex
> +    <resource action-id="eu.esdihumboldt.hale.io.schema.read.target" provider-id="eu.esdihumboldt.hale.io.xsd.reader">
Resolved by rebase to latest `master`

2022-01-11 09:20 UTC, JohannaOtt approved these changes
LGTM

2022-01-11 10:53 UTC, merged