Add AdV INSPIRE SLDs
wetransform/adv-inspire-alignments pull request #66
Opened 2023-02-02 14:01 UTC by Claudia-WE

Add AdV INSPIRE SLDs
For further clarification see: https://wetransform.atlassian.net/jira/servicedesk/projects/WGS/queues/custom/3/WGS-1356

2023-02-03 08:54 UTC, JohannaOtt requested changes
I added some comments to the changed files.
Additionally:
* As the WGS ticket is visible to AdV members anyway, I would have mentioned it in the commit message.
* The folder name "inspire-slds-master/inspire-slds-master" should be changed to "inspire-slds" or similar IMO

2023-02-03 08:54 UTC, JohannaOtt commented on inspire-slds-master/inspire-slds-master/.gitignore
> +# ignore files from eclipse editor
The gitignore file should not be pushed to the repository IMO.
It seems like they extracted the source folder from a github repository themselves and zipped them without removing the gitignore file but now, they only want to provide the files publicly.

2023-02-03 08:54 UTC, JohannaOtt commented on inspire-slds-master/inspire-slds-master/Vgl_SLD_AdV_ELF/ELF_SLDs.url
> +[{000214A0-0000-0000-C000-000000000046}]
I wonder if the "Vgl_SLD_AdV_ELF" folder should be made public as well. Might make sense to check back if the whole content of the zip file sent should be contained.

2023-03-13 11:35 UTC, Claudia-WE commented on inspire-slds-master/inspire-slds-master/Vgl_SLD_AdV_ELF/ELF_SLDs.url
> +[{000214A0-0000-0000-C000-000000000046}]
I would keep "Vgl_SLD_AdV_ELF" as I don't see any harm to keep it and it was provided in the ZIP

2023-03-14 08:03 UTC, JohannaOtt commented
@Claudia-WE Is it correct that these changes are covered in [this PR?](https://github.com/wetransform/adv-inspire-alignments/pull/68) Then this one should be closed.

2023-03-15 08:48 UTC, Claudia-WE commented
> Is it correct that these changes are covered in https://github.com/wetransform/adv-inspire-alignments/pull/68 Then this one should be closed.

Yes

2023-03-15 08:48 UTC, closed without merging